version: "3.8"

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
